services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    #env_file: 
      #- ./backend/.env
    environment:
      # fallback si no usás .env
      MONGODB_URL: mongodb://mongo:27017/iot_challenge
      PORT: "3000"
      HOST: "0.0.0.0"
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    profiles:
      - dev

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      NG_APP_API_URL: http://backend:3000
    depends_on:
      - backend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    profiles:
      - dev

  backend-test:
    build: ./backend
    container_name: backend-test
    environment:
      MONGODB_URL: mongodb://mongo:27017/iot_test
      PORT: "3000"
      HOST: "0.0.0.0"
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm test
    profiles:
      - test

  backend-coverage:
    build: ./backend
    container_name: backend-coverage
    environment:
      MONGODB_URL: mongodb://mongo:27017/iot_test
      PORT: "3000"
      HOST: "0.0.0.0"
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run test:coverage
    profiles:
      - test


volumes:
  mongo_data:
